### ISSUE TITLE
[FTR] support for pixelfed and stories support

### ISSUE THREAD

**Issue by Goldmaster** [austinhuang0131/barinsta#1112]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when instagram seams to be the most used, but is terrible for facebook. This app is very good. However support for pixelfed which is an opensource alternative to instagram would be nice to have.

**Describe the solution you'd like**
Support for login into pixelfed as well as support for posting a photo onto Instagram and pixelfed at the same time. Or 1 photo for either platform. As well support for scheduled posting would be nice. Finally support for posting to stories on Instagram and pixelfed at the same time would be nice.

**Additional context**
Support also for sharing stories to Facebook pages and Twitter fleets.

**Comment by austinhuang0131** [comment]
Barinsta is specifically designed for Instagram in terms of the backend (response, endpoints, etc.), so I will not implement Pixelfed due to the work required to address feature disparities. Though, you can use any Mastodon client to access Pixelfed since they're interoperable:

> Our v1 API is based on the mastodon v1 API (opens new window). You can reference the Mastodon documentation, we listed the differences below.

Yes, yes, we'll eventually implement posting stories, see #201 

I do not envision Barinsta as a social media toolkit so multi-platform posting is out of consideration, there's no reason to get people more addicted and give away more data
