### ISSUE TITLE
[FTR] Thanks for developing InstaGrabber. I have some suggestions to improve the app.

### ISSUE THREAD

**Issue by alin-1** [austinhuang0131/barinsta#122]
1. Sort the posts and stories in reverse chronological order (newest first). The default sorting of IG is a mess and they blend old and new posts / stories. This is by far the most important suggestion.
2. Add Next & Previous Profile buttons at the screen while watching stories. Basically there must be buttons to skip directly to the next or previous profile after deciding to not watch all stories from the current profile. 
3. Add an option to start the app with the main posts feed (the one on the left). It's getting annoying to see my profile so often after I start the app. 
4. Get rid of that stories ribbon bar and add a separate page for stories. Put pictures in this story page just like in the main posts feed. Usually there are way more story pictures than the post pictures and it's tiring to use that inefficient top stories ribbon.
5. There is an error with the Like button. It displays -1 before vote and 0 after. Please fix it. Also try to find a better color palette for buttons.
6. Add thumbnail view at the main posts feed.
7. Make the thumbnails a bit larger while watching a story. Currently they are barely visible.
8. Streamline the navigation. Add one bottom navigation bar that stays there all the time while the app is running. That navigation bar should include Posts, Stories, Profile, Discover, Search, More... (this one includes Settings, About, etc). You could remove those 3 small icons on top (Feed, Profile, Discover).
9. Add an option to display how many hours ago a post or story was posted instead of the actual time. e.g. posted 5 hours ago. Much more user friendly.
10. Add a solid background under the slide index (e.g. 1/4) when there are more pictures at a post. Currently they are not very visible.

Please consider these suggestions.

**Comment by austinhuang0131** [comment]
I'll answer them in the order as they're asked.

* Unfortunately, the API requires fetching in batches (currently 25 posts each), and because Facebook does sorting server-side, there is no guarantee that all items in the next batch is chronologically earlier than the previous batch (I don't follow a thousand public accounts to find it out), so that means I can only make it chronological within batches, which doesn't have too much uses, does it?
* There are already 2 buttons (DM & download) and I prefer not to squish another 2 buttons in.
* It's [intentional](https://github.com/humanetech-community/awesome-humane-tech/pull/29).
* I try not to deviate too much from the real app (Otherwise I'd end up with more confused user) so it'll probably stay that way...
* `-1`??? You might wanna show which post caused that. Also you can suggest a better palette by editing [this file](https://github.com/austinhuang0131/instagrabber/blob/master/app/src/main/res/values/color.xml).
* Again, I try not to deviate too much... But at least this one seems more doable (and might be convenient for many) than the story-ribbon one, so I might consider.
* How large??? Fit???
* This is being done in #77.
* I'd rather present data from the API accurately (ie. without alterations).
* Sure.

**Comment by alin-1** [comment]
I made a rough sketch with a more streamlined interface: [https://i.postimg.cc/wjpPvtC5/Untitled.png](url).

**Comment by ammargitham** [comment]
@austinhuang0131 Last point is done in #77 .

**Comment by austinhuang0131** [comment]
@alin-1 okay, fixed your format, now i see what you mean by prev/next buttons, yeah those are doable. Anyways, you forgot to consider DM, so for us it's DM-Feed-Profile-Discover-More..., and I have explained why I left out stories (also the story thumbnail is much smaller in your drawing, contradicting your own suggestion, unless I misunderstood), but thanks for your (other) contributions!

@ammargitham I guess you're doing 8 and 10 already, consider 2, 6 and 9 (as setting options), meanwhile I'll consider 1 and 5

**Comment by alin-1** [comment]
* Unfortunately, the API requires fetching in batches (currently 25 posts each), and because Facebook does sorting server-side, there is no guarantee that all items in the next batch is chronologically earlier than the previous batch (I don't follow a thousand public accounts to find it out), so that means I can only make it chronological within batches, which doesn't have too much uses, does it?

I'm using the IG downloader called StorySave and this one had reverse chronological sort for stories only. Basically the newest stories are displayed first as it should. Could you do that for stories?

* There are already 2 buttons (DM & download) and I prefer not to squish another 2 buttons in.

There is place on left and right of thumbnails. It would be very helpful.

* It's intentional.

But could you add an option to pick a different page? Most users are more interested in their posts feed. That should be the primary page in my opinion.

* I try not to deviate too much from the real app (Otherwise I'd end up with more confused users) so it'll probably stay that way... Also, since stories are fetched on a per-user basis (although the API does allow me to fetch up to 20 users in each request, it'll get suspicious), the number of stories in each scroll-batch changes, and it would present a significant challenge

The official app is terribly designed. I doubt most users would be confused by having a page with the items displayed in a vertical list instead of horizontal ribbon. Horizontal scroll is more difficult than vertical scroll.

* -1??? You might wanna show which post caused that.

Every single post. e.g.

[https://i.postimg.cc/1Xcq9jhZ/Instagrabber.jpg](url)

* Again, I try not to deviate too much... But at least this one seems more doable (and might be convenient for many) than the story-ribbon one, so I might consider.

OK.

* How large??? Fit???

Just a few pixels taller, respecting aspect ratio. It should take too much from the main image.

**Comment by ammargitham** [comment]
@austinhuang0131 Yeah. The start page will be configurable in the revamp. @alin-1 The like bug should also be fixed in #77.

**Comment by austinhuang0131** [comment]
By order of reply.

* It does seem possible to sort story bubbles by the timestamp of their *newest* story, therefore yes.
* Well I see how it is, now you have explained in the picture... So yes.
* Fine... See above.
* I guess now that you suggest a list, I could consider having collapsible groups on that list (so if you click a certain user then it'll show their story in the post-feed format within the list), but since I rejected having a stories tab, you probably still has to click one of the bubbles to access the list itself, which shouldn't be too hard (no horizontal scrolls).
* I am still curious what has caused that, because it certainly doesn't do that on my end...
* ok
* It *shouldn't*? I guess I could try experimenting with it...

fyi: the simple way to insert pictures is

```markdown
![](https://example.com/example.png)
```

**Comment by alin-1** [comment]
* It does seem possible to sort story bubbles by the timestamp of their newest story, therefore yes.

Yes, they are sorted by the newest story. That would be much better than the IG default chaos where it's hard to tell what are the new stories / posts.

* I guess now that you suggest a list, I could consider having collapsible groups on that list (so if you click a certain user then it'll show their story in the post-feed format within the list - similar uses exist on the follower comparison thing), but since I rejected having a stories tab, you probably still has to click one of the bubbles to access the list itself, which shouldn't be too hard (no horizontal scrolls).

Anything but the inefficient IG way of doing things would be preferable. Also previous/next buttons on the current story screen would prevent the need to always go back to the horizontal ribbon list, which is very tedious. That would be very appreciated.

When I made that suggestion with separate Stories page I was inspired by StorySave:

![StorySave](https://user-images.githubusercontent.com/13281020/92308780-f7410880-efa8-11ea-97dd-54b4f4f3031b.jpg)

I think this is a much better design than the crammed horizontal ribbon. But to each his own. That app is too limited and InstaGrabber has more features.

Also thanks for the GitHub tips. Keep up the good work.

**Comment by alin-1** [comment]
Another quick suggestion: at the watch story screen, is it possible to move the top bar (username, time, download, DM) below the thumbnails? That download button is used often and it's on top of the screen, a hard to reach place for most modern phones that are very tall.

**Comment by mario-g98** [comment]
Would it also be possible to add a like button directly in the feed and an option to see the people who have liked the post?

**Comment by austinhuang0131** [comment]
> add a like button directly in the feed

For anti-addiction reasons, no.

> an option to see the people who have liked the post

Eventually, yes.

**Comment by austinhuang0131** [comment]
![image](https://user-images.githubusercontent.com/16656689/98151542-54b8df00-1e9e-11eb-924b-cd48a364de81.png)

**Comment by austinhuang0131** [comment]
First message: Point 2, 3, 6, 8, 10 are there in #245. Point 5 is no longer applicable. That leaves point 1, 4, 7 and 9.

**Comment by alin-1** [comment]
Thanks for the hard work to improve this app. Could you add an option to make the bottom nav bar fixed or auto-hidden?

**Comment by austinhuang0131** [comment]
- [ ] Sort the posts and stories in reverse chronological order (newest first). The default sorting of IG is a mess and they blend old and new posts / stories. This is by far the most important suggestion.
- [ ] Get rid of that stories ribbon bar and add a separate page for stories. ~~Put pictures in this story page just like in the main posts feed. Usually there are way more story pictures than the post pictures and it's tiring to use that inefficient top stories ribbon.~~
- [ ] Make the thumbnails a bit larger while watching a story. Currently they are barely visible.
- [ ] Add an option to display how many hours ago a post or story was posted instead of the actual time. e.g. posted 5 hours ago. Much more user friendly.
- [ ] Add an option to make the bottom nav bar fixed or auto-hidden

**Comment by austinhuang0131** [comment]
moved to #458
