### ISSUE TITLE
[BUG] Error Not found!

### ISSUE THREAD

**Issue by iriman** [austinhuang0131/barinsta#1295]
- My app is on the latest version. barinsta_19.2.2-github_release.apk v19.2.2 "Beaver Tail" from github
- I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq).

## Steps
1. I try to add account by entering credentials and hit login,
2. enter code from authentication app and hit confirm.
3. Login page disappears and then I see an error message titled "Error" that says "Not found!"

![image](https://user-images.githubusercontent.com/8467903/119217087-0ba04380-baed-11eb-871c-c47b49096299.png)

Also whenever I tap on get cookies button I get a toast "Error loading cookies"

## Environment

 - Device: Samsung J510F
 - Android version: 7.1.1

**Comment by ammargitham** [comment]
You could try updating your system WebView.

**Comment by iriman** [comment]
Android System WebView was version 60 (that was working with a previous version of barinsta).
Now updated to version 90 from google play and logged in successfully.
Thanks!

**Comment by swiftSwathSee** [comment]
On some devices, the system WebView may be disabled and/or not easy to update (Chrome is used as the WV). But you can try installing Chrome Canary and temporarily using that as the WV, via the Andriod settings app in the developer options section.

Barinsta should maybe display the WebView version when it has this error, as a hint. And  check that it's using the correct WebView, because it almost seems like it somehow used the old system WV instead of the Chrome one.
