### ISSUE TITLE
[FTR] Other suggestions

### ISSUE THREAD

**Issue by alin-1** [austinhuang0131/barinsta#220]
First of all, congrats for the new interface of the new Barinsta. It looks professional and it's a significant improvement over the previous version. I have a few more suggestions based on v19.0-a2 besides those [older suggestions](https://github.com/austinhuang0131/barinsta/issues/122) that you considered:

1) Add an option at settings to make the bottom navigation bar fixed or auto hidden.

2) A single tap on DM / Feed / Profile / Discover loads those pages. What about a second tap on them to act as go to top of the page? It would be very helpful to have a way to scroll to top.

3) An option to display just a snippet of post description with a Read more... link. It could be turned on or off in settings.

4) A Toast bottom message after downloading an item from Feed or Discover. It's a quick and effective confirmation that a download succeeded.

5) A confirmation to exit the app after tapping the system's Back button on the main pages. It could be turned on or off in settings.

6) Slim grey lines between the posts in Feed. It helps differentiating the posts better.

7) The Back button doesn't work consistently. Sometimes the app exits instead of going back to the previous page.

8) At the Story screen make the header text (username + time) a bit smaller. This text overflows if an user is using a bigger font system wide.

9) Sometimes the bulk download doesn't work.

**Comment by austinhuang0131** [comment]
Point 2 duplicates #150.

Point 3: tbh I'd prefer the caption being un-scrollable until clicked, because obviously scrolling in a small window isn't ideal... So:

* click the non-scrollable caption box
* caption box expands to 80% (ish) of window and becomes scrollable
* add a translation button/span/wtv, per #178 

Point 8: afaik we do use the native `androidx.appcompat.app.ActionBar` so I don't think it can be scaled down

**Comment by alin-1** [comment]
About Point 3: what about an option in settings to hide descriptions and each post has a button to display the whole description at request? Obviously it should be turned on or off from settings. Many descriptions are too long and make the scrolling process more tedious than it should be.

**Comment by austinhuang0131** [comment]
> what about an option in settings to hide descriptions and each post has a button to display the whole description at request?

extreme edge case imo

> Many descriptions are too long and make the scrolling process more tedious than it should be.

well yeah that's why I said click-to-expand instead of scrolling in that small box

**Comment by alin-1** [comment]
OK. Keep up the good work.

**Comment by alin-1** [comment]
I have another suggestion: on the story screen now it's swipe left / right for previous / next story. What about swipe up / down for previous / next profile?

**Comment by ammargitham** [comment]
- [x] ~~Add an option at settings to make the bottom navigation bar fixed or auto hidden.~~
    _Bottom bar hides when scolling_
- [ ] A single tap on DM / Feed / Profile / Discover loads those pages. What about a second tap on them to act as go to top of the page? It would be very helpful to have a way to scroll to top.
   - [x] Feed
   - [ ] Profile
   - [ ] DM
   - [ ] Discover

- [x] ~~An option to display just a snippet of post description with a Read more... link. It could be turned on or off in settings.~~
  _Added in 19.0.0. All long captions are collapsed in the linear feed view._
- [ ] A Toast bottom message after downloading an item from Feed or Discover. It's a quick and effective confirmation that a download succeeded.
- [ ] A confirmation to exit the app after tapping the system's Back button on the main pages. It could be turned on or off in settings.
- [x] ~~Slim grey lines between the posts in Feed. It helps differentiating the posts better.~~
  _19.0.0 adds grid gap option which should hopefully solve this_
- [x] The Back button doesn't work consistently. Sometimes the app exits instead of going back to the previous page.
  _Only happens if the fragment transaction is slow and back is pressed multiple times. This should be a separate ticket imo._
- [x] ~~At the Story screen make the header text (username + time) a bit smaller. This text overflows if an user is using a bigger font system wide.~~
  _If the user has changed the font system wide, this would be a problem in all apps. Plus as @austinhuang0131 mentioned we use the actionbar to display the title. Maybe this can be taken in mind when the story ui overhaul is done in the future._
- [x] ~~Sometimes the bulk download doesn't work.~~
  _Download flow has been updated in 19.0.0. Should fix most downloading problems._

**Comment by austinhuang0131** [comment]
moved to #458
