### ISSUE TITLE
[FTR] Push notification and general notifications

### ISSUE THREAD

**Issue by hovercats** [austinhuang0131/barinsta#42]
As of 17.6 build DM's now work like expected, atleast to my knowledge. However, currently there is no clear indication of when a possible DM has been recieved other than remembering what people said. 
So heres a list of stuff which would improve this massivly

### **Highlight unread messenges in inbox.**
* This makes a clear indication of unread messenges when looking in inbox

###  **Have an indicator on 'main' screen (profile tab if logged in. This is also where DM is accessable.)**
* It would also be nice to have an indicator when scrolling down the feed aswell. I.eg  a disappearing tab saying youve recieved a new DM, or a display with the beginning of the actual DM and the respective name of the sender.
* notification of 'blocked' DMs (the requests you have to accept/deny). This could potentially just be a notification in the inbox itself, as its stock. (I personally dont care much for it, as I mostly recieve spam on this anyway, but people with private profiles might have more _action_ than I do, so they might appreciate this more than I do. 

### **Push notification.**
* This would obviously be used primarly for DM only, as app has no support for other stuff, unless you wish to implement notification when certain people post a new post or something along those lines. Like an rss feed of sort. I know FB have such a feature (unless it has been removed in the later years). 
* I belive using **Android Work** is a good implementation for reciving push notification. I seem to recall [Frost for facebook](https://github.com/AllanWang/Frost-for-Facebook) uses this, and push notifications work like expected with the ability to alter notification refresh rate (differing from 15 min to every other day) 
However, feel free to correct me if I got my info wrong here about Frost and Android Work.
If android work isnt useable, or there are better solutions, please find  solution as you see fit.

lastly, please for the love of all thats unholy, refrain from using those pesky permanent notification tabs that is used by alot of FOSS apps that have push notification of some sort.

This obviously takes time to implement, so take your time. Cheers.

**Comment by austinhuang0131** [comment]
Fixed formatting.

Rapid updates are exhausting so I'll rest for a while before trying to implement these features. Nevertheless, I'll set out the plan first.

* Highlight unread messenges in inbox doesn't sound so hard. However, viewing messages in IGBR currently does not mark them as read (unless you send a reply), so that means I probably need a "mark as read" function.
* I do not plan to add an unread count and I will opt for notifications instead (see below).
* I have not had a chance to experiment with accepting DMs, but I do plan to do it.
* Notifications:
  * Currently, Instagram account activity can be displayed (three dots => notifications) and I could make it check notification *count* at every app launch. I don't plan to constantly check that, however (anti-addiction).
  * I use Frost myself (for the stuff I have to use Facebook for, ugh college kids) and the notification format for DMs will be similar to theirs. I don't know about "Android Work".
* AFAIK Permanent notification is just to make sure the app doesn't get killed by battery saver and stuff, however in my opinion Instagram is not that important to be kept alive so it probably wouldn't happen

**Comment by landry314** [comment]
A design point here... You currently have in the menu a section called "Notifications" which is really "Activity". I suggest you rename this to "Activity" and move it to the bottom row like it is in Instagram (the heart icon).

Keeping this called notifications is confusing as it is but after you implement the ideas above it will be come even more confusing. I would love to see push notifications added to this app so I can stop using my web browser for that which gives me piles of notifications to swipe away. I would hope your notification system will combine notifications into one clean one! Thank you!

**Comment by austinhuang0131** [comment]
@landry314 it's called Activity now but it'll remain a section

**Comment by austinhuang0131** [comment]
In https://github.com/austinhuang0131/instagrabber/commit/4857b3bfa0ca33fc5c991be083d0e6855e252f97 activities should be notified

**Comment by austinhuang0131** [comment]
DM Notification is separated to #119

**Comment by landry314** [comment]
one little point... it is called "Activity" now but when you open Activity then at the top the title still says "Notifications"
