### ISSUE TITLE
[BUG] Can't login with Facebook

### ISSUE THREAD

**Issue by Sav22999** [austinhuang0131/barinsta#581]
- [x] My app is on the latest version. I understand that any other version is not supported.
- [x] I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq).

## Steps

1. Open app
2. "More" > "Add account"
3. Try login > Login with Facebook (it login successfully) redirect to Instagram which ask for the SMS code to login... the SMS arrives BUT the webpage is WHITE (like it's hidden)

## Environment

 - Device: LG G6 (H870)
 - Android version: 9

**Comment by rondaa** [comment]
I'm seeing this on Android 11, Pixel 4a 5G

**Comment by austinhuang0131** [comment]
This is actually broken on browser too: It'll load for a few seconds and return a white circle.

![Screen Shot 2021-02-23 at 22 16 58](https://user-images.githubusercontent.com/16656689/108942431-fc604580-7624-11eb-8127-616390632991.png)

So I can do nothing as the problem is entirely upstream. Your best bet would be to get a password.
