### ISSUE TITLE
[BUG] Feed isn't chronological.

### ISSUE THREAD

**Issue by Rozekail** [austinhuang0131/barinsta#670]
- [X] My app is on the latest version. I understand that any other version is not supported.
- [X] I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq).

## Description

Every now and then, the app will jumble up a bunch of posts and I'll get things that are days old ahead of brand new posts that I haven't seen yet. Hopefully this is a bug and not as intended, otherwise this post is in the wrong section.

## Steps

1. Launch app.
2. Go to Feed.
3. Sometimes it's jumbled, sometimes it isn't. I can't pinpoint a trigger or cause for it.

## Environment

 - Device: Samsung Galaxy A20
 - Android version: 10

**Comment by maguilara** [comment]
Yep, I was about to post this.  Device: Xiaomi Redmi Note 5, xiaomi.eu ROM. Android 9.

**Comment by austinhuang0131** [comment]
We pull data directly from Instagram's API. Since we do not tell them what you have seen out of privacy reasons (but also they want to know how many seconds you have been staring at each post, which is utter bs and will not be implemented whatsoever), their algorithm will not refresh the feed unless there are _enough_ (who knows how many) new posts.

related: https://redd.it/km43no

**Comment by maguilara** [comment]
@austinhuang0131 let met understand. So the feed is pulled from the API, and is sorted via a hidden algorithm which shows the feed in certain way, not necessarily in chronological order, meaning that chronological order will be impossible unless the API implements a request for chronologically sorted feed? Okay, got it.

**Comment by austinhuang0131** [comment]
The feed is sorted by an algorithm (well i mean it's facebook so it's completely expected). The feed can be changed if you tell Instagram what posts you've read. Doing so has privacy implications, but I could make it an optional setting (ie. tell Instagram you've read all posts in a fetch).

**Comment by maguilara** [comment]
@austinhuang0131 Yeah, I understand that, since I use Instagram as a source for news for certain institutions/stores, it's important for me to get the latest updates even if that meant a bit less of privacy. And if you have to also send the watch time for each post, I'd guess that it would be better if you gave all the posts the same amount of time (or around the same time to avoid being detected), as to throw off the algorithm and to treat equally all pages you follow.
