### ISSUE TITLE
[BUG] UI imprecision

### ISSUE THREAD

**Issue by MijoHuer** [austinhuang0131/barinsta#693]
- [x] My app is on the latest version. I understand that any other version is not supported.
- [x] I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq).

Is a "bug" of the UI (spanish version)
![Screenshot_20210216-192958_1_1](https://user-images.githubusercontent.com/78889806/108130445-6fe6dd80-708e-11eb-94e6-7e15c27a203e.png)
As you see, the "Tag" option does not enter correctly in the screen (using moto g5)

And also if the amount of post is big also happen
![Screenshot_20210216-194650_1_1](https://user-images.githubusercontent.com/78889806/108131413-fea82a00-708f-11eb-8ebe-df5b4883e563.png)

## Environment

 - Device: Moto G5 Cedric XT1677
 - Android version: 8.1.0

## Additional info
I want to say that, is the first time that i use this app, and i love it. I love your work. Have a nice day

**Comment by austinhuang0131** [comment]
Do you think it is possible to shorten those words in Spanish?

**Comment by MijoHuer** [comment]
I was thinking, but i dont found shorter words for "posts", "followers", "Tagged" and "Add to favorites"

**Comment by austinhuang0131** [comment]
So I changed the layout to this on master:

![signal-2021-03-05-143407](https://user-images.githubusercontent.com/16656689/110164800-e1799800-7dbf-11eb-988c-f0f4a71adbe6.jpeg)

As you can see, the "Favourite" button is given more space, allowing the string to be longer. The follow status (Mutual/Following/Follower) goes after the "(Un)Follow" button.

(The "Message" button should be after "Tagged", but it's disabled on master due to technicalities.)
