### ISSUE TITLE
Share To Feed Or Story Or DM To Users

### ISSUE THREAD

**Issue by landry314** [austinhuang0131/barinsta#756]
When you are looking at content on instagram on the web you can share that content directly in a message to a user. When you are viewing content in the app you can share it directly to a user OR to your story.

Barinsta does not have this feature at all as far as I can see.

Aside from sharing to a user via DM or to my story, I want to be able to quickly share posts that were tagged to me into my own feed. This would require it to be downloaded then reuploaded I am guessing but considering the instagrabber function is in this app, it could be done.

**Comment by austinhuang0131** [comment]
To story is probably not doable because story stickers are copyrighted\*, and sharing a post is probably a sticker, that's one of those lines I don't want to cross...

To DM duplicates #537.

<sup>\* "If you use content covered by intellectual property rights that we have and make available in our Service (for example, images, designs, videos, or sounds we provide that you add to content you create or share), we retain all rights to our content (but not yours)."</sup>

**Comment by landry314** [comment]
ok, not to story then, but to your own feed would be nice.
