### ISSUE TITLE
[FTR] Add an option to select some items to download in album instead of entire

### ISSUE THREAD

**Issue by Subbarao6338** [austinhuang0131/barinsta#818]
In one column layout, place like and save buttons along with download button.

Add an option to select in between 2 photos. 

Add reels and igtv tabs. And also download options for them.

**Comment by ammargitham** [comment]
1. Is same as #923 
2. Keeping this issue only for this request
3. Most likely won't be implemented.

**Comment by austinhuang0131** [comment]
1. Moved to #1376.
2. IMO the demand and benefits are both marginal. Still, #517 is implemented so it would be faster to download selected pages.
3. IGTV tabs will not be implemented since they do appear in feed and user pages. Since reels are no longer treated as regular posts, we'll implement it, but that's moved to #1241.
